# Type Name          ID  GECOS                         Home                                Shell
u ag-governor        -   "Agent Governor daemon"      /var/lib/agent-governor/agd         /usr/sbin/nologin
u ag-provider        -   "Agent Governor provider"    /var/lib/agent-governor/providerd   /usr/sbin/nologin
g ag-users           -
g ag-admin           -
